# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6022742e98591339beb79915018c9bc0205a89165ae886624f8c01d101b972c45610ca3ec5b1e18ef73d4263b0f0f23f5274572f7582385676832708a8b9ac69

test:
  secret_key_base: f610137c15572f9a7d8522f4e9620f4cd148a11cb6786c203d426da4c70437bf22268aab7edd6edbacf037cdfd03b61fed74fe0788634cee17e810cde867f2f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
